import React, { useState } from 'react';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import io from "socket.io-client";
import { FaCopy } from 'react-icons/fa';

import Chat from './Chat'
import './Login.css';

// const socket = io.connect("https://chatapp2-0.onrender.com");
const socket = io.connect("http://localhost:3001");

function Login() {
    const [name, SetName] = useState(''); // Username 
    const [hash, SetHash] = useState(''); // Room id used in socket.io
    const [showCopy, SetShowCopy] = useState(false) // showing copy button 
    const [showChat, SetShowChat] = useState(false) // showing chats
    const [isAdmin, setIsAdmin] = useState(false); // Track admin status
    const [roomLimit, SetRoomLimit] = useState('0')

    // helps to join the room using socket.io by emitting our unique hash
    const joinRoom = (e) => {
        e.preventDefault()
        const limit = parseInt(roomLimit);
        if (name !== "" && hash !== "" && limit >= 2 && limit <= 100) {
          socket.emit("join_room", hash, name);
          SetShowChat(true);
        }
      };


      const handleRoomLimitChange = (e) => {
        const inputValue = parseInt(e.target.value);
        if (inputValue >= 2 && inputValue <= 100) {
            SetRoomLimit(inputValue);
        } else {
            SetRoomLimit('0')
            toast.error("Please enter a number between 2 and 100.", {
                position: "top-right",
                autoClose: 3000, // Close the toast after 3 seconds
                hideProgressBar: true,
                closeOnClick: true,
                pauseOnHover: false,
                draggable: true,
            });
            console.log("Please enter a number between 2 and 100.");
        }
    };

    // creates hash and sets it 
    const handleHash = (e) => {
        e.preventDefault();
        const str = require('randomstring').generate({
            length: 100,
            charset: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890`~!@#$%^&*()-=_+{}[]:;",<.>?/|',
        });
        SetHash(str);
        SetShowCopy(true) 
        setIsAdmin(true) // Set admin status
    };

    // helps in copying the hash value generated by the system
    const copyHash = (e) => {
        e.preventDefault()
        const copyText = document.getElementById('hash-input');
        copyText.select();
        document.execCommand('copy');
    };

    return (
            <div>
                <ToastContainer />
            { 
                !showChat &&
                <div className="login-box">
                    <form>
                        <div className="user-box">
                            <input
                                type="text"
                                value={name}
                                placeholder="Username"
                                required
                                onChange={(e) => SetName(e.target.value)}
                            />
                        </div>
                        <div className="user-box">
                            <input
                                type="number"
                                // value={roomLimit}
                                placeholder="Max People in room"
                                required
                                onChange={handleRoomLimitChange}
                            />
                        </div>
                        <div className="user-box">
                            <input
                                type="text"
                                id="hash-input"
                                value={hash}
                                placeholder="Security Token (CONFIDENTIAL)"
                                onChange={(e) => SetHash(e.target.value)}
                                required
                            />
                            {
                                showCopy && 
                                <button onClick={copyHash} className="copy-button">
                                    Copy Hash<FaCopy /> {/* Copy icon */}
                                </button>
                            }
                        </div>
                        <center>
                            <button onClick={handleHash}>
                                Generate Hash
                            </button>
                            <button onClick={joinRoom}>
                                Chat
                            </button>
                        </center>
                    </form>
                </div>
            }
            {
                showChat &&
                <Chat
                    socket={socket}
                    name={name}
                    hash={hash}
                    isAdmin={isAdmin}
                />
            }
        </div>
    );
}

export default Login;
