import React, { useState } from 'react';
import io from "socket.io-client";
import { FaCopy } from 'react-icons/fa';

import Chat from './Chat'
import './Login.css';

// const socket = io.connect("https://chatapp2-0.onrender.com");
const socket = io.connect("http://localhost:3001");

function Login() {
    const [name, setName] = useState(''); // Username 
    const [hash, setHash] = useState(''); // Room id used in socket.io
    const [showCopy, SetShowCopy] = useState(false) // showing copy button 
    const [showChat, SetShowChat] = useState(false) // showing chats
    const [isAdmin, setIsAdmin] = useState(false); // Track admin status
    const [roomLimit, SetRoomLimit] = useState(0)

    // helps to join the room using socket.io by emitting our unique hash
    const joinRoom = (e) => {
        e.preventDefault()
        if (name !== "" && hash !== "") {
          socket.emit("join_room", hash, name);
          SetShowChat(true);
        }
      };

    // creates hash and sets it 
    const handleHash = (e) => {
        e.preventDefault();
        const str = require('randomstring').generate({
            length: 100,
            charset: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890`~!@#$%^&*()-=_+{}[]:;",<.>?/|',
        });
        setHash(str);
        SetShowCopy(true) 
        setIsAdmin(true) // Set admin status
    };

    // helps in copying the hash value generated by the system
    const copyHash = (e) => {
        e.preventDefault()
        const copyText = document.getElementById('hash-input');
        copyText.select();
        document.execCommand('copy');
    };

    return (
            <div>
            { 
                !showChat &&
                <div className="login-box">
                    <form>
                        <div className="user-box">
                            <input
                                type="text"
                                value={name}
                                placeholder="Username"
                                required
                                onChange={(e) => setName(e.target.value)}
                            />
                        </div>
                        <div className="user-box">
                            <input
                                type="number"
                                value={name}
                                placeholder="Username"
                                required
                                onChange={(e) => setName(e.target.value)}
                            />
                        </div>
                        <div className="user-box">
                            <input
                                type="text"
                                id="hash-input"
                                value={hash}
                                placeholder="Security Token (CONFIDENTIAL)"
                                onChange={(e) => setHash(e.target.value)}
                                required
                            />
                            {
                                showCopy && 
                                <button onClick={copyHash} className="copy-button">
                                    Copy Hash<FaCopy /> {/* Copy icon */}
                                </button>
                            }
                        </div>
                        <center>
                            <button onClick={handleHash}>
                                Generate Hash
                            </button>
                            <button onClick={joinRoom}>
                                Chat
                            </button>
                        </center>
                    </form>
                </div>
            }
            {
                showChat &&
                <Chat
                    socket={socket}
                    name={name}
                    hash={hash}
                    isAdmin={isAdmin}
                />
            }
        </div>
    );
}

export default Login;
